#pragma once

#include <stdexcept>

namespace nandroidfs {
	// Class for wrapping exceptions generated by the winsock API into std::exception
	class WinSockException : public std::exception {
	public:
		WinSockException(int err_code);

		const char* what() const throw();

		int get_err_code();
	private:
		std::string msg;
		int err_code;
	};

	// Throws a WinSockException if `return_value` is nonzero.
	void throw_if_nonzero(int return_value);
}