name: Build NandroidFS

on:
  push:
  pull_request:

jobs:
  build:
    name: Build installer 
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Install dependencies
      run: powershell ./install_deps.ps1
    - name: Build agent
      run: cd nandroid_daemon && powershell ./build.ps1
    - name: Build windows app
      run: msbuild /p:Configuration=Release
    - name: Standalone upload
      uses: actions/upload-artifact@v2
      with:
        name: standalone
        path: ./x64/Release/**